LEBAR = 1300
TINGGI = 750
TILE_SIZE = 50

HITAM = (0, 0, 0)
PUTIH = (255, 255, 255)

GREEN = (0, 200, 0)
YELLOW = (200, 200, 0)
RED = (200, 0, 0)

PLAYER_SPEED_NORMAL = 4
PLAYER_SPEED_MEDIUM = 6
PLAYER_SPEED_HARD = 8
PLAYER_SPEED_BOOST = 10

LIVES = 3
FPS = 60

GAME_STATE_MENU_AWAL = "MENU AWAL"
GAME_STATE_MENU = "MENU LEVEL"
GAME_STATE_PLAY = "PLAY"

LEVEL_EASY = "easy"
LEVEL_MEDIUM = "medium"
LEVEL_HARD = "hard"

GAME_STATE_WIN = "WIN"
GAME_STATE_OVER = "GAME_OVER"